apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent-management
    environment: Development
  name: agent-management
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: agent-management
  sessionAffinity: None
  type: ClusterIP
